include $(TOPDIR)/rules.mk

PKG_NAME:=usb-modem-huawei-eg162
PKG_VERSION:=0.1.0
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/usb-modem-huawei-eg162
  SECTION:=net
  CATEGORY:=Network
  TITLE:=Support for Huawei EG162 EDGE/GPRS USB Sticks
  MAINTAINER:=ePoint Systems Ltd <info@epointsystem.org>
  DEPENDS:=+usb-modem-huawei-e175x
endef

define Package/usb-modem-huawei-eg162/description
 Support for Huawei EG162 EDGE/GPRS USB Sticks
endef

define Build/Compile
endef

define Package/usb-modem-huawei-eg162/install
endef

$(eval $(call BuildPackage,usb-modem-huawei-eg162))
