#!/bin/sh

# Copyright (C) 2010 ePoint Systems Ltd.
# Author: Daniel A. Nagy

if [ -c /dev/ttyACM0 ]; then     # Linux 2.6
	uci set network.mobile.device=/dev/ttyACM0
elif [ -c /dev/usb/acm/0 ]; then # Linux 2.4
	uci set network.mobile.device=/dev/usb/acm/0
else                             # Error
	exit -1
fi
uci commit network
ifup mobile
