#!/bin/sh /etc/rc.common
# Copyright (C) 2009 OpenWrt.org
START=50

SSD=start-stop-daemon
NAME=tunslip
PIDF=/var/run/$NAME.pid
PROG=/usr/bin/$NAME
IFNAME=wpan0

start() {
	local ifname
	local ip6addr

	config_load network
	config_get ipaddr wpan0 ipaddr '192.168.119.1'
	config_get device wpan0 device '/dev/ttyUSB0'

	$SSD -S -m -p $PIDF -q -x $PROG -- -B 115200 -s $device -t $IFNAME $ipaddr &
}

stop() {
	$SSD -K -p $PIDF
}

