#!/bin/sh /etc/rc.common
# Copyright (C) 2009 OpenWrt.org
START=50

SSD=start-stop-daemon
NAME=tunslip6
PIDF=/var/run/$NAME.pid
PROG=/usr/sbin/$NAME
IFNAME=wpan0

start() {
	local ifname
	local ip6addr

	config_load network
	config_get ip6addr wpan0 ip6addr 'aaaa::1/64'
	config_get device wpan0 device '/dev/ttyUSB1'

	$SSD -S -m -p $PIDF -q -x $PROG -- -B 115200 -s $device -t $IFNAME $ip6addr &
	mc1322x-ctl -l flexibity reset
}

stop() {
	$SSD -K -p $PIDF
}

