#!/bin/sh /etc/rc.common
# Copyright (C) 2009 OpenWrt.org
START=50

SSD=start-stop-daemon
NAME=tunslip6
PIDF=/var/run/$NAME.pid
PROG=/usr/bin/$NAME

start() {
	local ifname
	local ip6addr

	config_load network
	config_get ifname sensors ifname 'wpan0'
	config_get ip6addr sensors ip6addr 'aaaa::1/64'

	mc1322x-reset.sh && sleep 3 && $SSD -S -m -p $PIDF -q -x $PROG -- -B 115200 -s /dev/ttyS1 -t $ifname $ip6addr &
}

stop() {
	$SSD -K -p $PIDF
}

