#!/bin/sh

# Copyright (C) 2010 ePoint Systems Ltd.
# Author: Daniel A. Nagy
# Based on /etc/hotplug.d/usb/10-usb, Copyright (C) 2009 OpenWrt.org

case "$ACTION" in
	add)
		[ -f /etc/usb-modeswitch/$PRODUCT ] &&
		(sleep 10 ; usb_modeswitch -c /etc/usb-modeswitch/$PRODUCT) &
		[ -f /etc/usb-modem.d/$PRODUCT ] &&
		. /etc/usb-modem.d/$PRODUCT
		;;
	remove)
		# nothing to do upon removal
		;;
esac
